# 국립국어원 데이터 읽기
1. 개체명 분석 말뭉치 2022 NE
2. 개체명 분석 말뭉치 개체 연결 2022 EL
3. 개체명 사전 2022 DX

In [4]:
import pandas as pd
import os

In [3]:
ne_path = "./data/korea/NIKL_NE_2022_CSV_개체명 분석"
el_path = "./data/korea/NIKL_EL_2022_CSV_개체 연결"
dx_path = "./data/korea/XXDX2200000001.csv"

In [17]:
def read_csv(path):
    if os.path.isdir(path):
        file_list = [file for file in os.listdir(path) if file.endswith(".csv")]
        result_df = pd.DataFrame()
        for file in file_list:
            df = pd.read_csv(os.path.join(path, file), index_col=0)
            result_df = pd.concat([result_df, df])
    else:
        result_df = pd.read_csv(path, index_col=0)
    return result_df

In [18]:
ne_df = read_csv(ne_path)
ne_df.head()

,file_id,doc_id,title,author,date,topic,sent_id,sent_form,NE_id,NE_form,NE_label,NE_begin,NE_end,original_topic
0,MXNE2202211218,MDRW2100000318.1,온라인 대화,개인 대화 참여자,20210819,가사 및 가족,MDRW2100000318.1.1,치킨시켜먹이까?,1,치킨,CV_FOOD,0,2,NaN
1,MXNE2202211218,MDRW2100000318.1,온라인 대화,개인 대화 참여자,20210819,가사 및 가족,MDRW2100000318.1.2,시켜먹던지 난 간단히 먹었어,[],[],[],[],[],NaN
2,MXNE2202211218,MDRW2100000318.1,온라인 대화,개인 대화 참여자,20210819,가사 및 가족,MDRW2100000318.1.3,name3이 먹고싶다니까,[],[],[],[],[],NaN
3,MXNE2202211218,MDRW2100000318.1,온라인 대화,개인 대화 참여자,20210819,가사 및 가족,MDRW2100000318.1.4,깊콘있으니깐 뿌링클,1,뿌링클,CV_FOOD,7,10,NaN
4,MXNE2202211218,MDRW2100000318.1,온라인 대화,개인 대화 참여자,20210819,가사 및 가족,MDRW2100000318.1.5,암꺼나 먹으세요,[],[],[],[],[],NaN

In [20]:
el_df = read_csv(el_path)
el_df.head()

/tmp/ipykernel_510856/80291844.py:6: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(path, file), index_col=0)

,file_id,doc_id,title,author,publisher,topic,date,sentence_id,sentence_form,NE_id,NE_form,NE_label,NE_begin,NE_end,NE_kid,NE_wikiid,NE_URL,original topic
0,SDEL2202211219,SDRW2000000006.1,2인 일상 대화,개인 발화자,개인 발화 녹음,"먹거리 > 맛집, 디저트, 차, 다이어트, 요리",20200602,SDRW2000000006.1.1.6,그래서 떡볶이,1,떡볶이,떡볶이,4,7,6160000001380.0,2359.0,https://ko.wikipedia.org/wiki/%EB%96%A1%EB%B3%...,NaN
1,SDEL2202211219,SDRW2000000006.1,2인 일상 대화,개인 발화자,개인 발화 녹음,"먹거리 > 맛집, 디저트, 차, 다이어트, 요리",20200602,SDRW2000000006.1.1.8,카레도,1,카레,카레,0,2,6160000004406.0,242332.0,https://ko.wikipedia.org/wiki/%EC%BB%A4%EB%A6%AC,NaN
2,SDEL2202211219,SDRW2000000006.1,2인 일상 대화,개인 발화자,개인 발화 녹음,"먹거리 > 맛집, 디저트, 차, 다이어트, 요리",20200602,SDRW2000000006.1.1.9,매운 카레를 좋아하고,1,카레,카레,3,5,6160000004406.0,242332.0,https://ko.wikipedia.org/wiki/%EC%BB%A4%EB%A6%AC,NaN
3,SDEL2202211219,SDRW2000000006.1,2인 일상 대화,개인 발화자,개인 발화 녹음,"먹거리 > 맛집, 디저트, 차, 다이어트, 요리",20200602,SDRW2000000006.1.1.10,돈가스를 먹어도,1,돈가스,돈가스,0,3,6160000001160.0,143195.0,https://ko.wikipedia.org/wiki/%EB%8F%88%EA%B0%...,NaN
4,SDEL2202211219,SDRW2000000006.1,2인 일상 대화,개인 발화자,개인 발화 녹음,"먹거리 > 맛집, 디저트, 차, 다이어트, 요리",20200602,SDRW2000000006.1.1.11,매운 돈가스를 좋아합니다.,1,돈가스,돈가스,3,6,6160000001160.0,143195.0,https://ko.wikipedia.org/wiki/%EB%8F%88%EA%B0%...,NaN

In [19]:
dx_df = read_csv(dx_path)
dx_df.head()

/tmp/ipykernel_510856/80291844.py:9: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  result_df = pd.read_csv(path, index_col=0)

,id,form,ne_label,ne_kid,ne_wikiform,ne_definition,ne_wikiLink,ne_SynonymGroup,example_id,example_form,example_NE_form,example_begin,example_end
0,1,(여자)아이들,PS_NAME,0,(여자)아이들,(여자)아이들((G)I-DLE)은 대한민국의 5인조 다국적 걸 그룹이다. 큐브 엔터...,https://ko.wikipedia.org/wiki/(%EC%97%AC%EC%9E...,"['아이들', '여자아이들']",NLRW2100000013.10045.4.1,"슈퍼주니어 이특과 배우 유이가 사회를 맡았고, 몬스타 엑스, 마마무, 오마이걸 승희...",(여자)아이들,67,74
1,2,10cm,QT_LENGTH,9020000000102,NaN,NaN,NaN,[],NLRW2100000013.7166.6.1,"시는 방류된 꽃게들이 1년 이후에는 10cm, 2년이 되면 15~17cm까지 자라는...",10cm,20,24
2,2,10cm,QT_LENGTH,9020000000102,NaN,NaN,NaN,[],MDRW2100004842.1.22,10cm 인형을 하나 샀는데 인형옷을 하나 사주려고요,10cm,0,4
3,2,10cm,QT_LENGTH,9020000000102,NaN,NaN,NaN,[],MDRW2100025523.1.4,키도 10cm넘게,10cm,3,7
4,2,10cm,PS_NAME,1,10cm (음악 그룹),10cm(십센치[1])는 대한민국의 1인조 인디 밴드이다.,https://ko.wikipedia.org/wiki/10cm_(%EC%9D%8C%...,"['10센치', '십센치']",MDRW2100014496.1.7,10cm요,10cm,0,4

In [21]:
len(set(dx_df['ne_label'])), set(dx_df['ne_label'])

(150,
 {'AFA_ART_CRAFT',
  'AFA_DOCUMENT',
  'AFA_MUSIC',
  'AFA_PERFORMANCE',
  'AFA_VIDEO',
  'AFW_OTHER_PRODUCTS',
  'AFW_SERVICE_PRODUCTS',
  'AF_BUILDING',
  'AF_CULTURAL_ASSET',
  'AF_MUSICAL_INSTRUMENT',
  'AF_ROAD',
  'AF_TRANSPORT',
  'AF_WEAPON',
  'AM_AMPHIBIA',
  'AM_BIRD',
  'AM_FISH',
  'AM_INSECT',
  'AM_MAMMALIA',
  'AM_OTHERS',
  'AM_PART',
  'AM_REPTILIA',
  'AM_TYPE',
  'CV_ART',
  'CV_BUILDING_TYPE',
  'CV_CLOTHING',
  'CV_CULTURE',
  'CV_CURRENCY',
  'CV_DRINK',
  'CV_FOOD',
  'CV_FOOD_STYLE',
  'CV_FUNDS',
  'CV_LANGUAGE',
  'CV_LAW',
  'CV_OCCUPATION',
  'CV_POLICY',
  'CV_POSITION',
  'CV_PRIZE',
  'CV_RELATION',
  'CV_SPORTS',
  'CV_SPORTS_INST',
  'CV_SPORTS_POSITION',
  'CV_TAX',
  'CV_TRIBE',
  'DT_DAY',
  'DT_DURATION',
  'DT_DYNASTY',
  'DT_GEOAGE',
  'DT_MONTH',
  'DT_OTHERS',
  'DT_SEASON',
  'DT_WEEK',
  'DT_YEAR',
  'EV_ACTIVITY',
  'EV_FESTIVAL',
  'EV_OTHERS',
  'EV_SPORTS',
  'EV_WAR_REVOLUTION',
  'FD_ART',
  'FD_HUMANITIES',
  'FD_MEDICINE',
  'FD_OTHERS',
  'FD_SCIENCE',
  'FD_SOCIAL_SCIENCE',
  'LCG_BAY',
  'LCG_CONTINENT',
  'LCG_ISLAND',
  'LCG_MOUNTAIN',
  'LCG_OCEAN',
  'LCG_RIVER',
  'LCP_CAPITALCITY',
  'LCP_CITY',
  'LCP_COUNTRY',
  'LCP_COUNTY',
  'LCP_PROVINCE',
  'LC_OTHERS',
  'LC_SPACE',
  'MT_CHEMICAL',
  'MT_ELEMENT',
  'MT_METAL',
  'MT_ROCK',
  'OGG_ART',
  'OGG_ECONOMY',
  'OGG_EDUCATION',
  'OGG_FOOD',
  'OGG_HOTEL',
  'OGG_LAW',
  'OGG_LIBRARY',
  'OGG_MEDIA',
  'OGG_MEDICINE',
  'OGG_MILITARY',
  'OGG_OTHERS',
  'OGG_POLITICS',
  'OGG_RELIGION',
  'OGG_SCIENCE',
  'OGG_SPORTS',
  'PS_CHARACTER',
  'PS_NAME',
  'PS_PET',
  'PT_FLOWER',
  'PT_FRUIT',
  'PT_GRASS',
  'PT_OTHERS',
  'PT_PART',
  'PT_TREE',
  'PT_TYPE',
  'QT_ADDRESS',
  'QT_AGE',
  'QT_ALBUM',
  'QT_CHANNEL',
  'QT_COUNT',
  'QT_LENGTH',
  'QT_MAN_COUNT',
  'QT_ORDER',
  'QT_OTHERS',
  'QT_PERCENTAGE',
  'QT_PHONE',
  'QT_PRICE',
  'QT_SIZE',
  'QT_SPEED',
  'QT_SPORTS',
  'QT_TEMPERATURE',
  'QT_VOLUME',
  'QT_WEIGHT',
  'TI_DURATION',
  'TI_HOUR',
  'TI_MINUTE',
  'TI_OTHERS',
  'TI_SECOND',
  'TMIG_GENRE',
  'TMI_EMAIL',
  'TMI_HW',
  'TMI_MODEL',
  'TMI_PROJECT',
  'TMI_SERVICE',
  'TMI_SITE',
  'TMI_SW',
  'TMM_DISEASE',
  'TMM_DRUG',
  'TM_CELL_TISSUE_ORGAN',
  'TM_CLIMATE',
  'TM_COLOR',
  'TM_DIRECTION',
  'TM_SHAPE',
  'TM_SPORTS',
  'TR_ART',
  'TR_HUMANITIES',
  'TR_MEDICINE',
  'TR_OTHERS',
  'TR_SCIENCE',
  'TR_SOCIAL_SCIENCE'})